### ISSUE TITLE
[Shattered Relic XP] Set effect icon has a progress bar

### ISSUE THREAD

**Issue by testing-ongithub** [Hydrox6/external-plugins#68] opened 2022-01-23 12:13 UTC
This issue is for the external plugin: [Shattered Relic XP]

My fast metabolism set effect icon has a progress bar as if it were a fragment (see image below).

<img width="45" alt="SetEffectProgress" src="https://user-images.githubusercontent.com/96100526/150677720-87b28818-bab1-4e9e-966f-61f8b67c0df2.png">

I have no idea what caused this, but none of the following fixed it:

- Turning the plugin off/on
- Disabling/enabling the "show progress bar" overlay option
  - Smaller thing that I don't care enough about to make a separate issue for but that I'll at least note here: Disabling the "show progress bar" overlay option doesn't immediately remove the progress bar overlay. I had to turn the plugin off/on for that change to take effect.
- Logging in/out
- Restarting the client
- Unequiping and then reequiping the fragments (when the fragments were removed and the set effect was gone, there wasn't a progress bar, but it was there again once I put them back on)

**Comment by Hydrox6** [comment] 2022-01-23 14:10
I've had this reported a couple of times, but I need a method to reproduce it; first report was it happening with Chain Magic, but it didn't break if I simply equipped relics to get Chain Magic.

**Comment by testing-ongithub** [comment] 2022-01-24 02:08
I tried to debug this without much luck. However, I did notice a few things that I'll report here just to document them _somewhere_.

**Related to this issue:**
-  The plugin seems to detect a fragment in use in the slot used by the set effect. 
   - It consistently detected the unholy ranger fragment for me (even if I changed the number of fragments equipped and/or equipped the unholy ranger fragment in another slot), but I don't know if that would be true for everyone with this issue.
   - <img width="600" alt="UnholyRangerSetEffect" src="https://user-images.githubusercontent.com/96100526/150710105-b498f55a-6835-4679-8b35-49951ffacead.png">

**Probably not related to this issue (but who knows) and very minor:**
- There was a NPE on line 283 of ShatteredRelicXPPlugin.java.
  - <img width="600" alt="NPE" src="https://user-images.githubusercontent.com/96100526/150710289-7fea65b8-5da2-4981-89db-86878b9462b3.png">
- There was an out of bound exception on line 385 of ShatteredRelicXPPlugin.java.
  - <img width="600" alt="OutOfBounds" src="https://user-images.githubusercontent.com/96100526/150710395-f17f65a1-76fe-4713-acd1-81ce18148cca.png">

**Comment by Hydrox6** [comment] 2022-01-24 02:22
Can you share what relics you're using for that first thing? I have a gut feeling about what it is, and I don't like it if it's that.

The NPE is odd, not sure why that would be happening, but it's not really that major I don't think.

The OoB will likely be due to the set effect tooltips being a single line. I'm messing with those eventually anyway, so it's not too big of a deal; I'll fix that at the same time.

**Comment by testing-ongithub** [comment] 2022-01-24 02:28
_Any fragments_ that together are enough for a set effect will result in a set effect with a progress bar, and the plugin always seems to thing the set effect is actually unholy ranger. If I have enough fragments to have multiple set effects, only the first one will have a progress bar.

Currently, I have Rogues' Chompy Farm, Arcane Conduit, Chef's Catch, Smooth Criminal, and Chinchonkers equipped (in that order), which results in Double Tap and Trailblazer (in that order). Double Tap has a progress bar that the plugin thinks is for Unholy Ranger.

**Comment by Hydrox6** [comment] 2022-01-24 02:39
![image](https://user-images.githubusercontent.com/2979691/150712844-e80d075c-99fb-4525-aaae-0833652143d0.png)
My theory now is that there's something fucky with your varbits compared to someone just logging in and equipping those relics. I'm not sure what exactly would cause that either. If it happens to you even after completely closing and restarting the client, then that's **extremely** weird and makes me even more confused about what's going on.

If you could get the values of each of the varbits between (and including) 13403 - 13409, that would be great

If it only happens after you've messed around with relics that session, the actions you took with your relics after logging in for the first time would also be appreciated.

**Comment by testing-ongithub** [comment] 2022-01-24 02:51
It does indeed happen after completely closing and restarting the client. 🍝 

Here's what I see after a fresh restart + login (I enabled the xp display just for this screenshot, and now I see that the set effect is marked as having 1xp. That's interesting):

<img width="259" alt="Fragments" src="https://user-images.githubusercontent.com/96100526/150714018-4677c5c4-a804-435f-a912-a983743a4d4d.png">

Varbits values:

- Varbit 13403: 0
- Varbit 13404: 0
- Varbit 13405: 1
- Varbit 13406: 0
- Varbit 13407: 86
- Varbit 13408: 4511
- Varbit 13409: 0

**Comment by Hydrox6** [comment] 2022-01-24 02:54
ah I made a goof with the varbits; those are the ones for xp per relic, not the slot contents :d

I would need the values of 13395 -> 13401

**Comment by testing-ongithub** [comment] 2022-01-24 02:58
Only the 4511 seems to match the fragment xp 😮 

Varbit 13395: 52
Varbit 13396: 6
Varbit 13397: 21
Varbit 13398: 23
Varbit 13399: 39
Varbit 13400: 3
Varbit 13401: 0

**Comment by Hydrox6** [comment] 2022-01-24 03:11
How the xp varbs work is that each relic has its own varbit. The order of them is the order I defined them in the enum (since it makes looking them up a lot easier), and it's the order they appear in the vanilla UI.

As for the slots, they store the index of what relic is in that slot (+1), with 0 meaning that nothing is in the slot.

As for the issue, I see it now: for whatever reason, 13400 *isn't* slot 6. It just skips a varbit for some reason. Not sure what could be being stored in that varb, and why mine is 0 but yours is 3, but that's an issue for another day. Thanks for cooperating with the debugging, this is not something I'd realistically have figured out entirely on my own.

**Comment by Hydrox6** [comment] 2022-01-24 03:26
Fixed in v1.4

**Closed by Hydrox6** 2022-01-24 03:26 UTC
Labels: bug, help wanted, shattered-relic-xp
