### ISSUE TITLE
[transmogrification] weird/incorrect rendering bugs

### ISSUE THREAD

**Issue by iligalodin** [Hydrox6/external-plugins#32] opened 2021-01-29 20:12 UTC
This issue is for the external plugin: transmogrification

Currently there is a bug with the head vanity slot and the arm vanity slot.

if you have your hair follow armor your head will become invisible when you don't have a worn helmet,
if you do have a helmet equipped it show your hair through the helmet
same goes for the arms, the arms become invisible when you have it set to follow armor and no body slot is equipped.
and if you do have a body armor equipped than you can see your arms through the armor.

**Comment by Hydrox6** [comment] 2021-01-29 20:26
duplicate of #31

**Closed by Hydrox6** 2021-01-29 20:26 UTC
