### ISSUE TITLE
[Inventory Summary] ability to hide the infobox when there is no items from whitelist/blacklist

### ISSUE THREAD

**Issue by WiggleNibble** [Hydrox6/external-plugins#89] opened 2022-08-17 08:54 UTC
This issue is for the external plugin: {Inventory Summary}
Plugin version: {1.2.1}
![image](https://user-images.githubusercontent.com/110086391/185077672-ee93aaab-de2e-4c9f-8677-c5a9120a9c3a.png)

**Comment by Enriath** [comment] 2022-08-17 08:56
Duplicate of #85

**Closed as completed by Enriath** 2022-08-17 08:56 UTC
Labels: duplicate
