### ISSUE TITLE
incorrect clue location

### ISSUE THREAD

**Issue by Covertpyro** [Hydrox6/external-plugins#21] opened 2020-11-24 02:04 UTC
this is a misthalin clue
![image](https://user-images.githubusercontent.com/9169955/100037044-97474a80-2dbe-11eb-9b16-c473420a4bde.png)

**Comment by Hydrox6** [comment] 2020-11-24 08:14
Duplicate of #16

**Closed by Hydrox6** 2020-11-24 08:14 UTC
