### ISSUE TITLE
[Contextual Cursor] Cursor renders behind menu in latest update

### ISSUE THREAD

**Issue by Kinomora** [Hydrox6/external-plugins#91] opened 2022-08-21 17:56 UTC
This issue is for the external plugin: Contextual Cursor
Plugin version: 1.3.0

The contextual cursor now hides behind the currently open right-click menu on the latest runelite version.

Without the plugin enabled:
![image](https://user-images.githubusercontent.com/9062578/185804135-be612ae3-bbfe-49d8-ac7d-38a69401064f.png)

With the plugin enabled:
![image](https://user-images.githubusercontent.com/9062578/185804156-e9ddd272-2635-47d1-aa23-f0de483e4ec6.png)

**Comment by Enriath** [comment] 2022-08-21 17:58
Duplicate of #90

**Closed as completed by Enriath** 2022-08-21 17:58 UTC
Labels: duplicate
