### ISSUE TITLE
[Shattered Relics XP] Show Progress Bar option doesn't work

### ISSUE THREAD

**Issue by Keilo104** [Hydrox6/external-plugins#76] opened 2022-02-09 17:28 UTC
This issue is for the external plugin: Shattered Relics XP
Plugin version: 1.7

Turning off "Show Progress Bar" under the "Overlay" section of configuration does nothing.

**Comment by Enriath** [comment] 2022-02-09 17:31
It definitely works for me. You're going to have to be more specific for reproduction steps.

**Comment by Keilo104** [comment] 2022-02-09 17:36
okay, tested some more stuff out, overall behavior is very finnicky

show progress bar doesn't work if you have text mode turned off, but if you turn on text mode, then you can turn off progress bar

on a similar manner, if you have text mode on and not progress bar, you can't turn text mode off, only if you turn progress bar on

hopefully that makes sense

**Comment by Enriath** [comment] 2022-02-09 17:39
oh I get what's happening now, yeah that's really fucky.

**Comment by Enriath** [comment] 2022-02-09 17:57
Fixed in 1.8

**Closed as completed by Enriath** 2022-02-09 17:57 UTC
Labels: bug, shattered-relic-xp
