### ISSUE TITLE
Plank Sack planks are counted multiple times when holding the "3" key in mahogany homes

### ISSUE THREAD

**Issue by dec0yable** [Hydrox6/external-plugins#92] opened 2022-09-01 09:39 UTC
This issue is for the external plugin: Plank Sack
Plugin version: 1.3.0
When doing mahogany homes, I just hold the 3 key to use teak planks, and spamclick whatever I'm trying to build.
Since I hold the 3 key it thinks it's building multiple times so the counter counts down 2 sometimes 3 times, so the counter becomes wrong.
I'd love for the plugin to only count it once when it's built so the counter is accurate.

**Comment by Enriath** [comment] 2023-03-16 02:43
Duplicate of #63

**Closed as completed by Enriath** 2023-03-16 02:43 UTC
Labels: duplicate
