### ISSUE TITLE
[Transmogrification] individually transmog items

### ISSUE THREAD

**Issue by geheur** [Hydrox6/external-plugins#38] opened 2021-02-24 10:02 UTC
This issue is for the external plugin: Transmogrification

It would be nice if you could apply different transmogs depending on what is equipped in that slot. That way when you switch gear your transmog will reflect your new gear, and you could do things like "upgrade" your ahrims robes into ancestral, without permanently wearing ancestral or having you change your transmog set every time you switch out of your mage gear.

This is different from #29, which wants to activate entire presets based on gear; this suggestion is for changing one slot in the transmog, based on the actual item you have equipped in that slot.

**Comment by Hydrox6** [comment] 2021-02-24 13:23
See, this is actually what #29 was asking for anyway, as noted in their first sentence. Either way, it's how it'll get implemented when I get around to it

Duplicate of #29

**Closed by Hydrox6** 2021-02-24 13:23 UTC
